language: ruby
rvm:
- 2.2.3
before_install:
- nvm install 4.2.3
- npm install
- npm install gulp-cli
- cd ./node_modules/uswds && npm install && gulp no-test build && cd ../../
- npm run build
- bundle config local.cloudgov-style ./gem/
install:
- bundle install
- bundle config local.cloudgov-style ./gem/
script: bundle exec jekyll build
after_script:
- gem install percy-cli
- percy snapshot _site/
branches:
  only:
  - master
  - 18f-pages
deploy:
  provider: npm
  email: msegreto@miceover.com
  on:
    branch: master
    tags: true
  api_key:
    secure: oyOysSf8T5ueZpaY0+HOqx6Suq/LONSoWI51qagw7Mjacn7KVn/vZtL5DtFn/E1SuXuPDmcTlkHZbDZhh52Kp0uWwB3YVcTKyps71glV9b2KUbKXa8J00Ml3sgK6sjVS9d68/rAUWfKET1+KJm5mQp352//Zuy+cnCX5bcDqzKh6qYOqoiWlKykc0QvoGu8FibeDvKwKUZCrFzecreX+EyWwAi8SvIZz7pgx8X/Q7i6UZAEmSSdY1zZw8mysf13Fk+xza7pJ5pHC++lOQ1RKEmiZSwa6DfSRQfpwxJuydNK2dZv/4b4gaya0/nW50Icpl/1NlPM7AG1lHKrUELOW886yeJ8TWy4kC3MjZD/zXQQNhwiBiH2XKNiUb7RNq/wyTmSJ4WdrxPAVWp1bItLoWNKYnPxc1uf+iGdAIsYsD8dtm2N38R63J+OaUfg3p93/042j3SOUN9HqSv+x2OnICT8t1ziPBEwzcT+BwSa4JXzCXABTMaoERSZOy9rXDCxVkIf/KKf0FajqcOAkEMQj+O/lnJ16qGKVVd9PAcUDW19RLdhtgV6I9qBkgbdCZLY4Bajil4G6UylpYcZpnYxKUMlL1QGYxSeoARe9qP7VKJ3Lsw7mRhBXUo/t1BTolIICi3xx2NWuwDqxWN9OKObHhs+vWLLuhhFOLBxnqJKykxA=
env:
  global:
    secure: NjAkBaViz8sUM0ChzQG5lR9ty7e6xYA3arFeQ3gVrlXwLMNJG6oN3dUKu2LjCHNIm4eTpM9EtR1ra+HwVt3BK7OGl+ebbHcROLPot1mCL8w8NW/bREW0KfZ1oq7wFdzSpinDZOS1ezfVMW+hah+rDVHNsiHoMq9wCNyThBiGGx55MOIkBmwJuJDBjuTTePmwOiRsFT6YWe5e3M5Z8xlzQjzaPN8PmxUv+kI8TXDUiFJ1018CZK7hUwQEXvcAQYlhvzPJ3FxnzIqdcF7UoGU8AFeqRZMy0DcWkNI5rMcWq0iqR0Jm5eUbB30S3WVko8wBYpwGKhQZl3lROzNj0eAwj0KwSeahDpfzJ+9SA5WDJDJ+IS0peed6n82DwuW39hVLf/aJo6SQEBY/QMklZ0LrDmq5AGl9vrSfE0nuxEs2TUyz9mkeTkrkMe6QhIe09NTrPBSN64gtg+oGl7Il1sut+xqJbBU2jvDMDmj+7nk3kA2ziX+LhWY/62ZQvljyntUIhKVhxkxBR55K09dSVZGZtx8OX/L3kWK527HUW5vYcb4fZhnmm1+v2aPpWr64me+RIUwddJLwDY0l+Ui22TwpcdO5TpnUKDLSOs4vRUuBpjRsu2WrEhwZPx2fxRLX4ZZhvQkSl5BlcXJ13lJjwVBc9jW2RouFdkQR3R0I1gePiW4=
