language: ruby
rvm:
- 2.2.3
before_install:
- nvm install 4.2.3
- npm install
- npm install gulp-cli
- cd node_modules/uswds && gem install scss-lint && npm install && gulp no-test copy-vendor-sass && cd ../../
- npm run build
- export USE_LOCAL_GEM=true
install:
- bundle install
script:
- npm run test
- bundle exec jekyll build
deploy:
  provider: npm
  email: msegreto@miceover.com
  on:
    tags: true
  api_key:
    secure: avWNC3KYWTHPcweQ68TslNDz3CQfRD8aSCbg1UkySeBVfbfh/7bCCtFfQNAl3Z8ZUEZHs44RGYcCQaYuUkAFWJuwCZKLFRy/VM4T26SfZTVVBdDFIWgtkdYsAhd9NxhPIceXpnyYwcLFFzEZybiKD5D+npWFIVxNvY1pkD1GPQWEZtt0PjBUMlhYlpaKNEaKY2qEuICK80JU0U+PqihM48Aq4/IoczVW/VTv9T19I1og76MqfGEfApzb1W1RBdCmspgimkTjgSrKDhLIBc8KRcMitAM4bCIiR+pKygrJTgpUi70vJftR7TcN5ClG3Cf0YhF83VERTpfv9l55+EkEuQYd/djIUr8rB/DiLSHVBU8XkLwlmJhQCBxfSDm55RXibmQhrHvqC0VaRWuQ7Qo/VbI9nxchp9Iy2wsyV4/eO8UochiF+U2Hg/b8h/JKu9SetuvuFjTXjH7yGtb6pCacTC4bJKdLQH8t2RKVS4cdQN/cYf8u65smDkO5YMTaXFyWpufgrndKTvaTgU9J5oOdlU2ZNQL87lHZhVRWfKR9CE7DiOukwr+KD4KnirG702Bnn5lU07UnsiRHD2qyvPSxoz2QrW1n3+GsQ1vNZ9Si2Eaer+Q5MT3ESIsDxvElsHnjaHCAl7DwwAT3ddK0Y1ZLRsYAJ7G5CIsEiQyOyZUu0Ic=
env:
  global:
    - secure: gfMbOT/o0FvMRjPljcvxxdEOWlyxKUY/UuIyUA9tNtQHhXYXAW6MZQ3R2kgNS+b8S5gnUr0nifuBqQzW5CQqKOWhkju+MhvYbTbW9pjLfzVIkdWNJwQ50lTQy28dPmBAQwM6CxEtZ6Gx4xyOkIVXQFmxLPZCh0QBef8UqCayO0MvKMigijG02wxFpm1A+OvFOsT0hgk9nenOAzGW0hyyLU+0qI54UWjr0N8dzDOTuwwcPr5fws9keAFrIsbaH5lo7Kmz9e0vOceYBhmsRKMRyrnxqYrHromuciX2Zy2wkECtoCGoEXMG/UTIaf/RuDPea27ahLx/Czr/4592azrfapP4qJf8oUgeOh8GCQf9tpTZoxWMYYMA9mOq7Qvr8/qJ2/diLZa1Ba7QvcjtUfe/8pddK38hOjh1T77UtqF0+YNXRapFoIND4i4FIuy7n/utwN2uOxKorbZ+NTgKXG4FPrO5NnqCc2OEeSXky8yW6R25JFGytUcl92cKoE1IgBmLCetc7rhvPmiSvo5QyKq1syzAs0+/ZiAW/mVOnh1WWB76gBhM1dqpbrMaUs4sEQtftTUyw6EqOCwF4xyp3u4o/dEg0kdS1BHB8ZrwEL3AkPU2amiJl5BqPoiO74jJR4GfHAJavi0zsky8tCyy+0y685Tp8zj4TPiNvfH4M9cPJJE=
    - secure: zkaHRM9STg7gDFVa9emheaZ5KmTUI69cuQIov/cUixA3jbsU1XS/E9nj3BotJf7hnsTLu0SQ8M5UbqTvVW2MypH9AYR/6EJaeTf4ZISVtxGjNxTyAzRuO7/YM2xYpCxwzebem1yWt7b0ap0UXyQU19pbQJBXwVqxNEMCnl/JrUqOZ6vuQk7qpFm4YlhvuHHUghBuwwNFxy28rb8tLBcFwyc1EQmR3NAzaHcRVhtOeW49GVCUKkUjTwKjg2w3mzCeLMOr8K7BcnoFox8BvMgogK+jyeakrqYGO28pb2TS1YeQbNyddp4obfX6dGWxtyUQ/jD2ucrX/9gvKSuE9qo/Edx5R8AdiGQ/tzj0/oZUo0lFdC0qOln0n6MXiub7q/a5MOhfWISFiqQtWDdMwwKAx/vKcaPbeZOgtQAOte5/nsoyzcTSdEs2LBtdRwGR4oG9twB4gXlFDsEvPA1pzw0GyG6j3wBq/Lz0H5Hz5zHmbbf8BdHATlThyN4c57RsIPo56uAFmCmM/QAWKzN0ptXuDDCMQvxRr3R7toPFtalU3fVAIkFazg0qyEy3Q9zv4pcPOj3tzgONPE4Gjq/2OaWlv4j80QpwqwepP49I1kxhUK5k3XHKwcjIzz+MIOVCD2BLfLf6Relea3TjMoSLiaWWt79ioEAVdBPrHeMDII3WiwU=

