language: ruby
rvm:
- 2.2.3
before_install:
- nvm install 4.2.3
- npm install
- npm install gulp-cli
- cd node_modules/uswds && gem install scss-lint && npm install && gulp no-test copy-vendor-sass && cd ../../
- npm run build
- export USE_LOCAL_GEM=true
install:
- bundle install
before_script:
- npm run test
- bundle exec jekyll build
branches:
  only:
    - /^release-.*$/
script:
- wget https://s3-us-west-2.amazonaws.com/screener-files/ci/v2/screener-ci.zip
- unzip screener-ci.zip
- wget https://s3-us-west-2.amazonaws.com/screener-files/screener-tunnel/screener-tunnel-client-linux-amd64.zip
- unzip screener-tunnel-client-linux-amd64.zip
- bundle exec jekyll serve &
- ./screener-tunnel-client -apikey="$SCREENER_API_KEY" -host="ci.server:4000" &
- ./screener-ci.sh $SCREENER_API_KEY $SCREENER_GROUP_ID $TRAVIS_BUILD_NUM
deploy:
  provider: npm
  email: msegreto@miceover.com
  on:
    tags: true
  api_key:
    secure: avWNC3KYWTHPcweQ68TslNDz3CQfRD8aSCbg1UkySeBVfbfh/7bCCtFfQNAl3Z8ZUEZHs44RGYcCQaYuUkAFWJuwCZKLFRy/VM4T26SfZTVVBdDFIWgtkdYsAhd9NxhPIceXpnyYwcLFFzEZybiKD5D+npWFIVxNvY1pkD1GPQWEZtt0PjBUMlhYlpaKNEaKY2qEuICK80JU0U+PqihM48Aq4/IoczVW/VTv9T19I1og76MqfGEfApzb1W1RBdCmspgimkTjgSrKDhLIBc8KRcMitAM4bCIiR+pKygrJTgpUi70vJftR7TcN5ClG3Cf0YhF83VERTpfv9l55+EkEuQYd/djIUr8rB/DiLSHVBU8XkLwlmJhQCBxfSDm55RXibmQhrHvqC0VaRWuQ7Qo/VbI9nxchp9Iy2wsyV4/eO8UochiF+U2Hg/b8h/JKu9SetuvuFjTXjH7yGtb6pCacTC4bJKdLQH8t2RKVS4cdQN/cYf8u65smDkO5YMTaXFyWpufgrndKTvaTgU9J5oOdlU2ZNQL87lHZhVRWfKR9CE7DiOukwr+KD4KnirG702Bnn5lU07UnsiRHD2qyvPSxoz2QrW1n3+GsQ1vNZ9Si2Eaer+Q5MT3ESIsDxvElsHnjaHCAl7DwwAT3ddK0Y1ZLRsYAJ7G5CIsEiQyOyZUu0Ic=
env:
  global:
  - secure: NjAkBaViz8sUM0ChzQG5lR9ty7e6xYA3arFeQ3gVrlXwLMNJG6oN3dUKu2LjCHNIm4eTpM9EtR1ra+HwVt3BK7OGl+ebbHcROLPot1mCL8w8NW/bREW0KfZ1oq7wFdzSpinDZOS1ezfVMW+hah+rDVHNsiHoMq9wCNyThBiGGx55MOIkBmwJuJDBjuTTePmwOiRsFT6YWe5e3M5Z8xlzQjzaPN8PmxUv+kI8TXDUiFJ1018CZK7hUwQEXvcAQYlhvzPJ3FxnzIqdcF7UoGU8AFeqRZMy0DcWkNI5rMcWq0iqR0Jm5eUbB30S3WVko8wBYpwGKhQZl3lROzNj0eAwj0KwSeahDpfzJ+9SA5WDJDJ+IS0peed6n82DwuW39hVLf/aJo6SQEBY/QMklZ0LrDmq5AGl9vrSfE0nuxEs2TUyz9mkeTkrkMe6QhIe09NTrPBSN64gtg+oGl7Il1sut+xqJbBU2jvDMDmj+7nk3kA2ziX+LhWY/62ZQvljyntUIhKVhxkxBR55K09dSVZGZtx8OX/L3kWK527HUW5vYcb4fZhnmm1+v2aPpWr64me+RIUwddJLwDY0l+Ui22TwpcdO5TpnUKDLSOs4vRUuBpjRsu2WrEhwZPx2fxRLX4ZZhvQkSl5BlcXJ13lJjwVBc9jW2RouFdkQR3R0I1gePiW4=
  - secure: RGwuGOX70elAQQgxyzCOKKzYtTPiqKmJwzvta8eOiTnj6a3LtY/3zpkhcwwXz0f2qIa/GcLUYIPKDY4wd9wF7zteAQRv/UQC90ZYxDcilmt7y1dEa5WcqqYzAhjw5llS4f+5hbaXit4KE/el/1W8MvY4/zzBVbym/LNLkBvtcZd4bBnD8bLSbT4seAV0Sx+RgsQ7+5n7Tg0Ve1bz9mojjlUr4pZf5+2rY2m+5O26coB0Dw1uiNEbVWEAjZsh9EczKIa9Nd0tbQniG2yEpNX9GOGC4SV09JRLM9SdOaL5GBaDUF0511oHtlhGUj58IpPwQu0yjUyYXThEuhc/z47LCoDjkXIlg/OK2vdJ58KMhe9lgYdD5hbu7qwdKZhelshXDypF8R7NAXCuGdxk8UES5RbSowh6kwuzmNdW/GOPwPukTEeFrt+EZlIbp77YBHcdCMS12Lg+ooa4N7acVhwFo29872jA+prqTbubeh2MVvM8zQdUO0uzIzehNgNc1wC1kjDZq/0/gBV7aDM7Leh63u0RtZOa4AHBxyuj9izPVLT31G+HTnYUyurtJjExuo4JYoed0nAz1ARJzrFwZDrU5Q5kW/QTS9d8LDzc7jPWyP7wblMQ7A/y1TOPJfrTeb/HvUyuraKNSsyp8Az/wEwpqB3F0pu9cKEmWrIgmHC2VUI=
  - secure: h2+ZS22Qn2ovkqfScKdooN3Tcmi4sdIUF7zTC31GOpQ0JOXmCVzC1eFdPhnaFVgVZiiYlq6uANoodum0fz2XB8Ud+sr325995dji2Jqdb3ODLUuXWkDWdt5O7HPb146I2WOfXmRdK0Efq/mAjd+/22Pxmuh4mCnb3jmuevFDiCBPw68Kq3m6yAN7zYuWp+LXG9YCd+kekZKswaEugoQ2MlQLYxJPS6N+KgNrAmCXYyVdWMx3yhUb8kCft9zJLtftoMEivqQ59+k9gmjo4X8MpZCBNYtevtSQPIX9Sq2cDtjkOVUen1KlLt0IbnSfFdkbnpnIjhb8cQL8pKzATKlNxOlEANJuB3eVZh4FVO3Zor6Vrf7gf5TdoiTeqHZIU6nHa0esJtBfMCtO5sZy25Ff+I/3rbmICglju9dY91ZnT2nLaQe23OYpV9e6YK47/E/sb4Fex/30GKyjSHPbEwBKbNVqjvX5PtJZ4wmGBnWvhOsKnTazr+bTnb74Q8lb11pwtikF/INPFfnoR7oLpSNVoqDr1AS/eL6oHD+uheuMPcywy+xtnZO6/2q4cTlVFkHhy2Ab1ZP8Iw5ZZi4/926fY5YTC55yCDMKJG56JQlntkblqCSeGPdWvGCekog+x87PZYHMEXQDrwc9YCBUKFZoq+08CtfSCL3zdiv8/5gR8cw=
