title: Icon Ui
status: beta
collated: true
default: chevron-left

variants:
  - name: chevron-left
    context:
      iconKind: chevron
      iconOrientation: left
  - name: chevron-right
    context:
      iconKind: chevron
      iconOrientation: right
  - name: chevron-down
    context:
      iconKind: chevron
      iconOrientation: down
  - name: chevron-up
    context:
      iconKind: chevron
      iconOrientation: up
