title: count-status
status: wip
context:
  status: alt
  kind: kind
  kindIcon: kindIcon
  kinds:
    - kind:
      name: name
variants:
  - name: default
  - name: space
    context:
      status: alt
      kind: space
      kindIcon: space
      kinds:
        - kind:
          name: name
  - name: app
    context:
      status: ok
      kind: app
      kindIcon: app
      kinds:
        - kind:
          name: name
  - name: service
    context:
      status: alt
      kind: service
      kindIcon: service
      kinds:
        - kind:
          name: name
