title: Buttons
variants:
  - name: default
  - name: warning
    context:
      modifier: warning
  - name: primary
    context:
      modifier: primary
  - name: cautious
    context:
      modifier: cautious
  - name: finish
    context:
      modifier: finish
