title: Status Pill
status: beta
collated: true

variants:
  - name: default
    context:
      text: "success"
      modifier: success
      patternbreak: "<br/>"
  - name: warning
    context:
      text: "warning"
      modifier: warning
      patternbreak: "<br/>"
  - name: error
    context:
      text: "error"
      modifier: error
      patternbreak: "<br/>"
