title: card-home-contents
status: wip
context:
  organizations:
    - org:
      name: 'abacus'
      spaces:
        - space:
          name: 'foo/foo'
        - space:
          name: 'foo/bar'
      apps:
        - app:
          name: 'foo/foo'
        - app:
          name: 'foo/bar'
    - org:
      name: 'epa-journeyman'
      spaces:
        - space:
          name: 'bar/foo'
    - org:
      name: 'sandbox'
      spaces:
        - space:
          name: 'sandbox/user.name'
