title: Icon Ui Light
status: beta
collated: true
default: chevron-left-white
preview: '@preview-bg-dark'

variants:
  - name: chevron-left-white
    context:
      iconKind: chevron
      iconOrientation: left
      iconWhite: true
  - name: chevron-right-white
    context:
      iconKind: chevron
      iconOrientation: right
      iconWhite: true
  - name: chevron-down-white
    context:
      iconKind: chevron
      iconOrientation: down
      iconWhite: true
  - name: chevron-up-white
    context:
      iconKind: chevron
      iconOrientation: up
      iconWhite: true
