title: count-status
status: wip
context:
  entityKind: space
  status: alt
  entityCount: '1'
variants:
  - name: default
  - name: space
    context:
      entityKind: space
      status: alt
      entityCount: '3'
  - name: app
    context:
      entityKind: app
      status: ok
      entityCount: '4'
  - name: service
    context:
      entityKind: service
      status: alt
      entityCount: '0'
