title: Page header
preview: '@preview-bg'
status: beta
context:
  title: Overview
variants:
  - name: with-icon
    context:
      title: todo-list-space-dev
      icon: space
  - name: with-actions
    context:
      title: todo-list-app
      icon: app
      buttonText: Restart app
