title: icon-ui
collated: true
variants:
  - name: default
  - name: org-small
    context:
      iconKind: org
      iconSize: small
      isBorder: false
  - name: org-medium
    context:
      iconKind: org
      iconSize: medium
      isBorder: false
  - name: org-large
    context:
      iconKind: org
      iconSize: large
      isBorder: false
  - name: org-active-small
    context:
      iconStatus: active
      iconKind: org
      iconSize: small
      isBorder: false
  - name: org-active-medium
    context:
      iconStatus: active
      iconKind: org
      iconSize: medium
      isBorder: false
  - name: org-active-large
    context:
      iconStatus: active
      iconKind: org
      iconSize: large
      isBorder: false
  - name: org-disabled-small
    context:
      iconStatus: disabled
      iconKind: org
      iconSize: small
      isBorder: false
  - name: org-disabled-medium
    context:
      iconStatus: disabled
      iconKind: org
      iconSize: medium
      isBorder: false
  - name: org-disabled-large
    context:
      iconStatus: disabled
      iconKind: org
      iconSize: large
      isBorder: false
  - name: space-small
    context:
      iconKind: space
      iconSize: small
      isBorder: true
  - name: space-medium
    context:
      iconKind: space
      iconSize: medium
      isBorder: true
  - name: space-large
    context:
      iconKind: space
      iconSize: large
      isBorder: true
  - name: space-disabled-small
    context:
      iconStatus: disabled
      iconKind: space
      iconSize: small
      isBorder: true
  - name: space-disabled-medium
    context:
      iconStatus: disabled
      iconKind: space
      iconSize: medium
      isBorder: true
  - name: space-disabled-large
    context:
      iconStatus: disabled
      iconKind: space
      iconSize: large
      isBorder: true
  - name: space-active-small
    context:
      iconStatus: active
      iconKind: space
      iconSize: small
      isBorder: true
  - name: space-active-medium
    context:
      iconStatus: active
      iconKind: space
      iconSize: medium
      isBorder: true
  - name: space-active-large
    context:
      iconStatus: active
      iconKind: space
      iconSize: large
      isBorder: true
  - name: space-ok-small
    context:
      iconStatus: ok
      iconKind: space
      iconSize: small
      isBorder: true
  - name: space-ok-medium
    context:
      iconStatus: ok
      iconKind: space
      iconSize: medium
      isBorder: true
  - name: space-ok-large
    context:
      iconStatus: ok
      iconKind: space
      iconSize: large
      isBorder: true
  - name: space-error-small
    context:
      iconStatus: error
      iconKind: space
      iconSize: small
      isBorder: true
  - name: space-error-medium
    context:
      iconStatus: error
      iconKind: space
      iconSize: medium
      isBorder: true
  - name: space-error-large
    context:
      iconStatus: error
      iconKind: space
      iconSize: large
      isBorder: true
  - name: app-small
    context:
      iconKind: app
      iconSize: small
      isBorder: true
  - name: app-medium
    context:
      iconKind: app
      iconSize: medium
      isBorder: true
  - name: app-large
    context:
      iconKind: app
      iconSize: large
      isBorder: true
  - name: app-disabled-small
    context:
      iconStatus: disabled
      iconKind: app
      iconSize: small
      isBorder: true
  - name: app-disabled-medium
    context:
      iconStatus: disabled
      iconKind: app
      iconSize: medium
      isBorder: true
  - name: app-disabled-large
    context:
      iconStatus: disabled
      iconKind: app
      iconSize: large
      isBorder: true
  - name: app-active-small
    context:
      iconStatus: active
      iconKind: app
      iconSize: small
      isBorder: true
  - name: app-active-medium
    context:
      iconStatus: active
      iconKind: app
      iconSize: medium
      isBorder: true
  - name: app-active-large
    context:
      iconStatus: active
      iconKind: app
      iconSize: large
      isBorder: true
  - name: app-ok-small
    context:
      iconStatus: ok
      iconKind: app
      iconSize: small
      isBorder: true
  - name: app-ok-medium
    context:
      iconStatus: ok
      iconKind: app
      iconSize: medium
      isBorder: true
  - name: app-ok-large
    context:
      iconStatus: ok
      iconKind: app
      iconSize: large
      isBorder: true
  - name: app-error-small
    context:
      iconStatus: error
      iconKind: app
      iconSize: small
      isBorder: true
  - name: app-error-medium
    context:
      iconStatus: error
      iconKind: app
      iconSize: medium
      isBorder: true
  - name: app-error-large
    context:
      iconStatus: error
      iconKind: app
      iconSize: large
      isBorder: true
  - name: service-small
    context:
      iconKind: service
      iconSize: small
      isBorder: true
  - name: service-medium
    context:
      iconKind: service
      iconSize: medium
      isBorder: true
  - name: service-large
    context:
      iconKind: service
      iconSize: large
      isBorder: true
